import { useState } from 'react';
import { Box, Container, Divider, Typography } from '@mui/material';
import Navbar from './Navbar';
import FileUpload from './FileUpload';
import WebPageInput from './WebPageInput';
import TextInput from './TextInput';
import CollectedItems from './CollectedItems';
import OutputDisplay from './OutputDisplay';

function Dashboard() {
  const [items, setItems] = useState([]);
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleAddItem = (item) => {
    setItems([...items, item]);
  };

  const handleRemoveItem = (index) => {
    setItems(items.filter((_, i) => i !== index));
  };

  const handleSubmit = async () => {
    setLoading(true);
    setError('');
    setOutput('');

    try {
      // Simulate API call - replace with actual API integration
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Mock output
      const mockOutput = `# Study Guide Generated from ${items.length} Sources

## Overview
This comprehensive study guide has been generated by fusing content from multiple sources including PDFs, web articles, and text inputs.

## Key Concepts

${items.map((item, idx) => `
### Source ${idx + 1}: ${item.type.toUpperCase()}
- Name: ${item.name}
- Type: ${item.type}
`).join('\n')}

## Summary
This study guide represents a synthesized view of all the materials you've provided. In a production environment, this would contain the actual merged and processed content from your sources.

## Next Steps
1. Review the content above
2. Add more sources if needed
3. Export or save your study guide

---
Generated by Auto-Note Fusion`;

      setOutput(mockOutput);
    } catch {
      setError('Failed to generate study guide. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}>
      <Navbar />
      
      <Container maxWidth="xl" sx={{ py: 4 }}>
        <Typography variant="h4" sx={{ mb: 4, color: 'text.primary', fontWeight: 600 }}>
          Dashboard
        </Typography>

        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' },
            gap: 3,
          }}
        >
          {/* Input Section */}
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
            <FileUpload onAdd={handleAddItem} />
            <WebPageInput onAdd={handleAddItem} />
            <TextInput onAdd={handleAddItem} />
          </Box>

          {/* Collected Items Section */}
          <Box>
            <CollectedItems
              items={items}
              onRemove={handleRemoveItem}
              onSubmit={handleSubmit}
            />
          </Box>
        </Box>

        {/* Output Section */}
        {(output || loading || error) && (
          <>
            <Divider sx={{ my: 4 }} />
            <Typography variant="h5" sx={{ mb: 3, color: 'text.primary', fontWeight: 600 }}>
              Output
            </Typography>
            <OutputDisplay output={output} loading={loading} error={error} />
          </>
        )}
      </Container>
    </Box>
  );
}

export default Dashboard;
